name: README updates with the latest blog posts

on:
 schedule:
   # Every hour at minute 0
   - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://medium.com/feed/alan
          readme-section: feed
          empty-commits: 'false'
          branch: acceptance
          path: 'profile/README.md'
